spring:
  config:
    import:
      - optional:classpath:/config/
      #      - optional:classpath:/config/local/
      - optional:classpath:/config/localdb/
      #      - optional:classpath:/config/dev/
      #      - optional:classpath:/config/prod/
  application:
    name: demo
  profiles:
    default: local-db
    group:
      local-db: local-db, local-db-liquibase
  #      local:
  #      dev:
  #      prod: